# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2013, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------


## This file defines parameters for a prediction experiment.

###############################################################################
#                                IMPORTANT!!!
# This params file is dynamically generated by the RunExperimentPermutations
# script. Any changes made manually will be over-written the next time
# RunExperimentPermutations is run!!!
###############################################################################


from nupic.frameworks.opf.expdescriptionhelpers import importBaseDescription

# the sub-experiment configuration
config ={
  'aggregationInfo' : {'seconds': 0, 'fields': [], 'months': 0, 'days': 0, 'years': 0, 'hours': 0, 'microseconds': 0, 'weeks': 0, 'minutes': 0, 'milliseconds': 0},
  'modelParams' : {'sensorParams': {'encoders': {'_classifierInput': {'classifierOnly': True, 'clipInput': True, 'n': 275, 'fieldname': 'classification', 'w': 21, 'type': 'AdaptiveScalarEncoder'}, u'field8': None, u'field9': None, u'field2': None, u'field3': None, u'field1': {'name': 'field1', 'minval': -100000.0, 'clipInput': True, 'n': 272, 'fieldname': 'field1', 'w': 21, 'type': 'AdaptiveScalarEncoder'}, u'field6': None, u'field7': None, u'field4': None, u'field5': None, u'field10': None, u'field11': None, u'field12': None, u'field13': None, u'field14': None, u'field15': None, u'field16': None, u'field17': None, u'field18': None, u'field19': None, u'field20': None}}, 'spParams': {}, 'tpParams': {}, 'clParams': {'alpha': 0.050050000000000004}},

}

mod = importBaseDescription('../description.py', config)
locals().update(mod.__dict__)
